"""remove the testing age column

Revision ID: eef37acdb1ec
Revises: d00eb8cbfc91
Create Date: 2020-01-20 12:56:22.833250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eef37acdb1ec'
down_revision = 'd00eb8cbfc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
